FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /neo4j

RUN pip3 install \
    typer==0.12.3 \
    neo4j==5.27.0 \
    --break-system-packages

CMD ["tail", "-f", "/dev/null"]